### ISSUE TITLE
Rendering area small?

### ISSUE THREAD

**Issue by tarokudo360** [sebleedelisle/ofxLaser#24]
Thanks for the great library.

I'm using the Helios Laser DAC for laser animation, but the rendering area is very small. (The rendering area is probably less than half of the limit of a galvanometer scanner.)

Is there any way to make it render a larger area than 800PX?

**Comment by sebleedelisle** [comment]
Thanks! By default the output is small, you can stretch it out in the output zone view - hit tab in the examples and adjust the points.

**Comment by tarokudo360** [comment]
Hi
Thank you for reply.
Looking at the code, it seems that there is some kind of calculation error in the following code, but I am not familiar with the C language and could not figure out what is wrong.

If you have time, I would appreciate it if you could check it out.

HeliosDac.cpp Line 135
frameBuffer[bufPos++] = (points[i].x >> 4);
frameBuffer[bufPos++] = ((points[i].x & 0x0F) << 4) | (points[i].y >> 8);
frameBuffer[bufPos++] = (points[i].y & 0xFF);

**Comment by sebleedelisle** [comment]
Hi there, I’ll look into it but what makes you think there’s a calculation error in that part of the code?

**Comment by sebleedelisle** [comment]
In my tests today I can confirm that I'm getting the full range output from the HeliosDac. I would check the output zone settings within the compiled app. Or I'd be happy to look at your code if you want to package up your entire folder and send it over. 

I'm gonna close this issue for now but please do send me your code if you still have trouble. 

(The snippet of code is actually the part that converts the RGB colour into bytes -the data format for the Helios is weird in that it uses 2d vectors for colour components, so that's probably why you thought that code was suspicious, but it's not 😊 )
