### ISSUE TITLE
Revert option to programatically add lasers and dacs

### ISSUE THREAD

**Issue by adminfriso** [sebleedelisle/ofxLaser#25]
Hi Seb,
I am working with Gijs on his project.

In the project we use the sendRawPoints on the 3 lasers we have. this method uses the lasernumber as value.
Because the lasers cannot programatically be set now with the new version, we can never make sure they are set. 
Currently I get a vector out of range in the update loop. As the update loop starts running directly after boot and directly tries to send points to a laser that does not exist yet.
If we revert the option to programatically set the lasers (with dac (IP) setup) it is again possible to setup the laser setup at application startup. I think this can work the same way as the add laser button in the gui does.

What are your thoughts about this?
Greetings Friso

**Comment by sebleedelisle** [comment]
Hey Friso,

Thanks for letting me know about this. My suggestion is :

1 : Let me fix the code so it doesn't throw an error when the laser number
is out of range
2 : You can set up the 3 lasers within the app... every time you run it
from now on the 3 will be set up.
3 : Choose the relevant etherdream from the dropdown menu in the laser
settings (it no longer relies on IP address so will always find the DAC
based on its MAC address)

When you restart the app, the etherdream allocation should be remembered by
the system. But for now you will have to click the "Refresh controller
list" button as it doesn't always find the ether dreams during the start up
process. (I will fix this in a later release so that the dac list will be
updated automatically as they are discovered).

Hope this helps!

Seb

**Comment by adminfriso** [comment]
I think this would be a good solution, I'm looking forward to the fix.

**Comment by sebleedelisle** [comment]
OK I've implemented those changes, let me know if they work for you!

**Comment by sebleedelisle** [comment]
I'm gonna close this for now, let me know if you have any more issues, thanks!

**Comment by adminfriso** [comment]
works like a charm! thanks!
