### ISSUE TITLE
Adobe Illustrator created SVG files are not displayed

### ISSUE THREAD

**Issue by eighteight** [sebleedelisle/ofxLaser#35]
In the attachment I put an example of an SVG file, created in Adobe Illustrator, using "File" -> "Export As"–>"SVG" options:
<img width="470" alt="Screenshot 2022-05-06 at 3 16 48 PM" src="https://user-images.githubusercontent.com/542368/167129718-f14206c4-5d5b-48bd-a8cc-01c32361e8c6.png">

This file does not throw any errors while read in ofxLaser SVG example, but does not render either.

What is the recommended workflow for creating SVG files for usage in ofxLaser?

Thanks
![laser-test](https://user-images.githubusercontent.com/542368/167129832-22e27cb1-bfe5-428e-a964-c0d3cbd334b4.svg)
[laser-test.svg.zip](https://github.com/sebleedelisle/ofxLaser/files/8639901/laser-test.svg.zip)

**Comment by sebleedelisle** [comment]
Hi there, 

the system uses libtinysvg (the same as in ofxSvg) and it's very fussy! I've added additional parsing to catch some common insufficiencies in the library but it's still a bit temperamental. 

Try exporting from AI in SVGTiny format - it should be one of the options (although I no longer have AI so can't test). Otherwise use Inkscape which seems to work better. 

If you want more detail, It seems that the issue in your SVG is the style definition (it seems to work when the style definition is inline - see attached example) so you can always manually edit them if you continue to have issues. Hope this helps! 

Seb 
![laser-test6](https://user-images.githubusercontent.com/110866/167135361-1cb11c01-58c1-4e52-aa6f-b69d8f1f6c41.svg)

**Comment by eighteight** [comment]
@sebleedelisle svgtiny 1.1 option in AI works!
<img width="473" alt="Screenshot 2022-05-06 at 4 25 29 PM" src="https://user-images.githubusercontent.com/542368/167140463-400a0be1-1fce-4a53-82da-4574ece111cb.png">

Thanks a lot for your help!
[laser-test1.svg.zip](https://github.com/sebleedelisle/ofxLaser/files/8640314/laser-test1.svg.zip)

**Comment by sebleedelisle** [comment]
Glad I could help!
