### ISSUE TITLE
No laser controller found

### ISSUE THREAD

**Issue by larry104** [sebleedelisle/ofxLaser#41]
Hi,

after seeing what you are creating with Liberation I was really curious about ofxLaser. I compiled it under Ubuntu 22.04. And after lengthy debugging I got it to run (needed to add ofxSvg to addons.make and run make with LDFLAGS="-lusb-1.0", I also needed to add `#include <stack>` into libs/ofxImGui/src/ImHelpers.h). Anyway, all example run but every example shows "No laser controller found" even after clicking on Refresh controller list. I have one Etherdream2 connected to the network and can ping the IP address so, I know it's there. Any advise on how to debug this?

**Comment by larry104** [comment]
I found the issue ... it was related to a firewall setting.  the Etherdream is found now but the refresh rate is for some reason very slow so, the output kind of blinks like the green square of the controller becomes red and then green again. I am not sure if that is related to the fact that it runs on a virtual machine and maybe that affects the network speed.

**Comment by sebleedelisle** [comment]
Glad you sorted the connectivity! Blinking could be caused by so many
thing! Bad network, too many points being sent, the Scan Fail Safety system
on the laser, slow point rate...

Bad network : is the green square next to the laser in the Laser Overview
window changing colour? If it's steady green then that's good.
Too many points : does it happen on all the demos? What are you sending?
Scan Fail Safety : not sure if you know but most lasers have a system that
cut out the laser when the scanners aren't moving. It's usually a button on
the back.
Slow point rate : try changing the laser speed and point rate (you
shouldn't need to go above 30,000 ops)

Hope this helps.

**Comment by larry104** [comment]
Thanks a lot.  I was running all your examples and reducing the number of pps makes it a little better ... So, I am pretty sure it's the network related to the VM I am running. 

Quick question ... If I draw a triangle with it's midpoint in 0,0 (all corners are on a circle though 0,0) and translate it to the center 400/400  e.g.

`	 triangle.addVertex(glm::vec3(ax,ay,0));
	 triangle.addVertex(glm::vec3(bx,by,0));
	 triangle.addVertex(glm::vec3(cx,cy,0));
	 triangle.addVertex(glm::vec3(ax,ay,0));
	 ofPushMatrix();
    ofTranslate(400,400);
    ofRotateYRad(ofGetElapsedTimef());
	 laser.drawPoly(triangle, ofColor::red, OFXLASER_PROFILE_DEFAULT);
	 laser.drawDot(ax,ay, ofColor::white, 1.0, OFXLASER_PROFILE_FAST);
	 laser.drawDot(bx,by, ofColor::white, 1.0, OFXLASER_PROFILE_FAST);
	 laser.drawDot(cx,cy, ofColor::white, 1.0, OFXLASER_PROFILE_FAST);
    ofPopMatrix();` 

The animation of the rotation looks kind of distorted as if I am looking at it from top and not at the origin ... does that make sense? What am I missing here?
![image](https://github.com/sebleedelisle/ofxLaser/assets/2013720/b96b360c-881f-4cf9-ad1b-5f6e49a2680c)

**Comment by sebleedelisle** [comment]
I'm not sure what you're trying to do here, sorry. It's probably something to do with 3D projection though, check the 3D example in example_LaserEffects. There may also be some issues with 3D projection.
